version: "3.7"
services:
  frontend:
    build: frontend
    expose:
      - 8000
    depends_on:
      - express

  backend:
    restart: always
    build: backend
    depends_on:
      - mongo_settings_db
      - postgres_tiles_db
    links:
      - mongo_settings_db
      - postgres_tiles_db
    expose:
      - 27015

    environment:
      - dev=1
      - mongo_settings_db_container_name=mongo_settings_db
      - postgres_tiles_db_container_name=postgres_tiles_db
      - postgres_tiles_db_name=rainbow_database
      - postgres_tiles_db_user_name=unicorn_user
      - postgres_tiles_db_user_password=magical_password
      - postgres_tiles_db_port=5432

  mongo_settings_db:
    restart: always
    image: mongo:5.0.2
    expose:
      - 27017
    container_name: mongo_settings_db
    volumes:
      - mongo_settings_db_data:/var/lib/home-portal-server/mongo_settings_db_data/
      - ./make_settings_mongo_db.js:/docker-entrypoint-initdb.d/make_settings_mongo_db.js:ro

  postgres_tiles_db:
    restart: always
    image: postgres:13.3
    expose:
      - 5432
    container_name: postgres_tiles_db
    env_file:
      - postgres_tiles_db.env
    volumes:
      - postgres_tiles_db_data:/var/lib/home-portal-server/postgres_tiles_db_data/ # persist data even if container shuts down
      - ./make_links_postgres_table.sql:/docker-entrypoint-initdb.d/make_links_postgres_table.sql

volumes:
  postgres_tiles_db_data: # named volumes can be managed easier using docker-compose
  mongo_settings_db_data: