version: "3.7"
services:
  frontend:
    build: frontend
    expose:
      - 8000
    depends_on:
      - express

  express:
    restart: always
    build: backend
    depends_on:
      - mongo
      - postgres
    links:
      - mongo
      - postgres
    expose: 
      - 27015

  mongo:
    restart: always
    image: mongo:5.0.2
    expose:
      - 27017

  postgres:
    restart: always
    image: postgres:13.3
    expose:
      - 27016