version: "3.7"
services:
#  frontend:
#    build: frontend
#    expose:
#      - 8000
#    depends_on:
#      - express

  backend:
    restart: always
    build: backend
    depends_on:
      - mongo_settings_db
#      - postgres_tiles_db
    links:
      - mongo_settings_db
#      - postgres_tiles_db
    expose: 
      - 27015

    environment:
      - dev=1
      - mongo_settings_db_container_name=mongo_settings_db
      - postgres_tiles_db_container_name=postgres_tiles_db

  mongo_settings_db:
    restart: always
    image: mongo:5.0.2
    expose:
      - 27017
    container_name: mongo_settings_db

  postgres_tiles_db:
    restart: always
    image: postgres:13.3
    expose:
      - 5432
    container_name: postgres_tiles_db
    env_file:
      - postgres_tiles_db.env